# https://ci.appveyor.com/project/olegsych/chronology/settings/yaml

version: "{build}"

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - master

skip_tags: true

image: Visual Studio 2019

clone_script:
- ps: >-
    if(-not $env:APPVEYOR_PULL_REQUEST_NUMBER) {
      git clone -c core.symlinks=true --branch=$env:APPVEYOR_REPO_BRANCH https://github.com/$env:APPVEYOR_REPO_NAME.git $env:APPVEYOR_BUILD_FOLDER
      cd $env:APPVEYOR_BUILD_FOLDER
      git checkout -qf $env:APPVEYOR_REPO_COMMIT
    } else {
      git clone -c core.symlinks=true https://github.com/$env:APPVEYOR_REPO_NAME.git $env:APPVEYOR_BUILD_FOLDER
      cd $env:APPVEYOR_BUILD_FOLDER
      git fetch -q origin +refs/pull/$env:APPVEYOR_PULL_REQUEST_NUMBER/merge:
      git checkout -qf FETCH_HEAD
    }
- cmd: git submodule update --init --recursive

build_script:
- cmd: dotnet build .\Chronology.sln -nologo -logger:"C:\Program Files\AppVeyor\BuildAgent\dotnetcore\Appveyor.MSBuildLogger.dll"

test_script:
- cmd: dotnet test .\tests\Tests.csproj

after_test:
- cmd: dotnet pack .\src\Chronology.csproj --configuration Release --include-symbols

artifacts:
- path: bin\release\*.*nupkg
