# https://ci.appveyor.com/project/olegsych/chronology/settings/yaml

version: "{build}"

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - master

skip_tags: true

image: Visual Studio 2019

clone_script:
- cmd: git clone --recurse-submodules -q -c core.symlinks=true https://github.com/olegsych/chronology.git .\
- ps: >-
    if($env:APPVEYOR_PULL_REQUEST_NUMBER) {
        git fetch -q origin +refs/pull/$env:APPVEYOR_PULL_REQUEST_NUMBER/merge:
        git checkout --recurse-submodules -qf FETCH_HEAD
    } else {
        git checkout --recurse-submodules -qf $env:APPVEYOR_REPO_COMMIT
    }
- cmd: git log -2

build_script:
- cmd: dotnet build .\Chronology.sln -nologo -logger:"C:\Program Files\AppVeyor\BuildAgent\dotnetcore\Appveyor.MSBuildLogger.dll"

test_script:
- cmd: dotnet test .\tests\Tests.csproj

after_test:
- cmd: dotnet pack .\src\Chronology.csproj --configuration Release --include-symbols

artifacts:
- path: bin\release\*.*nupkg
